/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gmail_hackwaly_nc1020_NC1020_JNI */

#ifndef _Included_gmail_hackwaly_nc1020_NC1020_JNI
#define _Included_gmail_hackwaly_nc1020_NC1020_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gmail_hackwaly_nc1020_NC1020_JNI
 * Method:    Initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gmail_hackwaly_nc1020_NC1020_1JNI_Initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gmail_hackwaly_nc1020_NC1020_JNI
 * Method:    Reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmail_hackwaly_nc1020_NC1020_1JNI_Reset
  (JNIEnv *, jobject);

/*
 * Class:     gmail_hackwaly_nc1020_NC1020_JNI
 * Method:    Load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmail_hackwaly_nc1020_NC1020_1JNI_Load
  (JNIEnv *, jobject);

/*
 * Class:     gmail_hackwaly_nc1020_NC1020_JNI
 * Method:    Save
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmail_hackwaly_nc1020_NC1020_1JNI_Save
  (JNIEnv *, jobject);

/*
 * Class:     gmail_hackwaly_nc1020_NC1020_JNI
 * Method:    SetKey
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_gmail_hackwaly_nc1020_NC1020_1JNI_SetKey
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     gmail_hackwaly_nc1020_NC1020_JNI
 * Method:    RunTimeSlice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmail_hackwaly_nc1020_NC1020_1JNI_RunTimeSlice
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     gmail_hackwaly_nc1020_NC1020_JNI
 * Method:    CopyLcdBuffer
 * Signature: ([C)V
 */
JNIEXPORT jboolean JNICALL Java_gmail_hackwaly_nc1020_NC1020_1JNI_CopyLcdBuffer
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
